import { test, expect } from "bun:test";
import { mkdtempSync, writeFileSync, readFileSync, readdirSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { init } from "../src/core/scaffold/scaffold.ts";
import { load } from "../src/core/config/config.ts";
import { validate } from "../src/core/validate/validate.ts";
import { agentsMD } from "../src/core/contract/contract.ts";
import { buildManifest } from "../scripts/gen-embedded.ts";

const repoRoot = join(import.meta.dir, "..");

function tmp(): string {
  return mkdtempSync(join(tmpdir(), "init-"));
}
function errors(dir: string): number {
  return validate(dir, load(dir)).filter((f) => f.severity === "error").length;
}

test("init (core) round-trips to zero errors", () => {
  const dir = tmp();
  const res = init(dir);
  expect(res.created.length).toBeGreaterThan(0);
  expect(res.alreadyInit).toBe(false);
  expect(res.created).toContain(".ibuildos.yaml");
  expect(res.created).toContain("CLAUDE.md");
  expect(errors(dir)).toBe(0);
});

test("init --full round-trips to zero errors (whole taxonomy)", () => {
  const dir = tmp();
  init(dir, { full: true });
  expect(statSync(join(dir, "docs/types/user.md")).isFile()).toBe(true);
  expect(errors(dir)).toBe(0);
});

test("init --example (core and full) round-trips to zero errors", () => {
  const c = tmp();
  init(c, { example: true });
  expect(statSync(join(c, "docs/requirements/req-0001.md")).isFile()).toBe(true);
  expect(errors(c)).toBe(0);
  const f = tmp();
  init(f, { example: true, full: true });
  expect(errors(f)).toBe(0);
});

test("init is idempotent and never overwrites user edits", () => {
  const dir = tmp();
  init(dir);
  const cfgPath = join(dir, ".ibuildos.yaml");
  const sentinel = "root: docs\n# user edit\n";
  writeFileSync(cfgPath, sentinel);
  const res2 = init(dir);
  expect(res2.alreadyInit).toBe(true);
  expect(res2.created.length).toBe(0);
  expect(readFileSync(cfgPath, "utf8")).toBe(sentinel); // untouched
});

// --- Drift gate: templates/.claude must byte-match plugin/ ---
function claudeSource(rel: string): string | null {
  if (rel === "settings.json") return join(repoRoot, "plugin", "hooks", "hooks.json");
  if (rel.startsWith("skills/")) return join(repoRoot, "plugin", rel);
  if (rel.startsWith("agents/")) return join(repoRoot, "plugin", rel);
  return null;
}
function walk(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p, base));
    else out.push(relative(base, p).replaceAll("\\", "/"));
  }
  return out;
}

test("TestClaudeMirror: vendored .claude is byte-identical to plugin/", () => {
  const mirror = join(repoRoot, "templates", ".claude");
  for (const rel of walk(mirror)) {
    const src = claudeSource(rel);
    expect(src, `unmapped mirror file ${rel}`).not.toBeNull();
    expect(readFileSync(join(mirror, rel)), rel).toEqual(readFileSync(src!));
  }
  // no silent drops: every plugin skill/agent is mirrored
  const pluginDir = join(repoRoot, "plugin");
  for (const rel of [...walk(join(pluginDir, "skills"), pluginDir), ...walk(join(pluginDir, "agents"), pluginDir)]) {
    expect(statSync(join(mirror, rel)).isFile(), rel).toBe(true);
  }
});

test("TestEmbedFresh: embedded.ts matches the generator output", () => {
  const onDisk = readFileSync(join(repoRoot, "src", "core", "scaffold", "embedded.ts"), "utf8");
  expect(onDisk).toBe(buildManifest());
});

test("agents (AGENTS.md) is data-driven off ChainConfig", () => {
  const cfg = load(repoRoot);
  const doc = agentsMD(cfg, "test");
  expect(doc).toContain("`implements`");
  expect(doc).toContain("`verified_by`");
  expect(doc).toContain("Generated by iBuildOS test.");
  expect(doc).toContain("AGENTS.md — iBuildOS");
});
