// Package contract emits the iBuildOS "contract surface": a deterministic,
// taxonomy-blind description of what the binary is and how OTHER coding agents
// and tools should drive it. It is AI-free and has no module dependencies — it
// reads the resolved ChainConfig and renders stable Markdown.
//
// AgentsMD rides the AGENTS.md convention: a single Markdown file at a repo's
// root that tells an agent how to work in this project. Because every
// relationship/field/status name comes from cfg.Chain (never a literal type
// name like "Task"), an alternate profile documents itself with zero code
// change.
package contract

import (
	"fmt"
	"strings"

	"github.com/PurnaOS/iBuildOS/internal/config"
)

// AgentsMD renders the AGENTS.md document for a bundle's resolved config. Output
// is deterministic: identical inputs yield byte-identical Markdown. version is
// the build version (e.g. cli.Version); it is recorded so an agent can pin the
// contract it read against.
func AgentsMD(cfg config.Config, version string) string {
	ch := cfg.Chain
	var b strings.Builder

	w := func(format string, a ...any) {
		if len(a) == 0 {
			b.WriteString(format)
		} else {
			fmt.Fprintf(&b, format, a...)
		}
		b.WriteByte('\n')
	}

	w("# AGENTS.md — iBuildOS")
	w("")
	w("iBuildOS is a **deterministic, AI-free traceability linter** for the")
	w("Requirement -> Task -> Code -> Test chain. Artifacts are OKF documents:")
	w("git-native Markdown files with YAML frontmatter. The linter is the single")
	w("source of truth for whether the chain is complete; it makes no network")
	w("calls and runs no AI.")
	w("")
	w("This file follows the [AGENTS.md](https://agents.md) convention so any")
	w("coding agent or tool can drive iBuildOS by pointing at the binary and its")
	w("graph. It is generated by `iBuild agents` from the project's resolved")
	w("configuration; do not hand-edit.")
	w("")
	w("Generated by iBuildOS %s.", version)
	w("")

	w("## Commands")
	w("")
	w("Use the `iBuild` binary. These are the surfaces an agent should drive:")
	w("")
	w("- `iBuild validate [path]` — the **deterministic gate**. Exit code `0` means")
	w("  the chain is clean; exit code `1` means there are errors. Run this before")
	w("  declaring any work done; never bypass it. Add `--format json` for a stable")
	w("  machine report.")
	w("- `iBuild graph [path]` — the typed link graph as JSON: the **fast-context")
	w("  oracle** for reasoning about the bundle. It computes no findings and is not")
	w("  a gate. Flags:")
	w("    - `--node <ref>` focus on one node (root-relative key) and its neighborhood")
	w("    - `--depth N` neighborhood radius when `--node` is set")
	w("    - `--rel a,b` restrict to these relationship names")
	w("    - `--body excerpt|full|none` how much node prose to include")
	w("- `iBuild site [path] [--out <file>]` — render a self-contained, offline HTML")
	w("  traceability + planning UI (human-facing).")
	w("- `iBuild serve [path]` — run iBuild Studio: a localhost UI plus JSON oracles")
	w("  (`/graph`, `/validate`, `/config`, `/catalog`) and an AI-free `/simulate`.")
	w("")

	w("## The chain contract")
	w("")
	w("Completeness rules key off these relationship and field names, resolved from")
	w("this project's configuration (an alternate profile renames them and this")
	w("document follows):")
	w("")
	w("| Role | Name |")
	w("| --- | --- |")
	w("| work-fulfils-requirement relationship | `%s` |", ch.ImplementsRel)
	w("| test-checks-requirement relationship | `%s` |", ch.VerifiesRel)
	w("| work-covered-by-test relationship | `%s` |", ch.VerifiedByRel)
	w("| work-rolls-up-to-work relationship | `%s` |", ch.ParentRel)
	w("| code field (globs to source files) | `%s` |", ch.CodeField)
	w("")
	w("Status vocabularies (the one unavoidable value coupling):")
	w("")
	w("- active requirement statuses: %s", codeList(ch.ActiveReqStatuses))
	w("- proposed statuses: %s", codeList(ch.ProposedStatuses))
	w("- done statuses: %s", codeList(ch.DoneStatuses))
	w("- passing statuses: %s", codeList(ch.PassingStatuses))
	w("")

	w("## Rules for agents")
	w("")
	w("- Artifacts are git-native files. Edit the Markdown + frontmatter directly;")
	w("  state lives in git, never in a sidecar.")
	w("- Never bypass `iBuild validate`. It is the source of truth for the chain;")
	w("  if it reports errors, the work is not done.")
	w("- Use `iBuild graph` as your fast-context oracle before editing, so you")
	w("  reason over the actual typed link graph rather than guessing.")
	w("- AI authoring is **suggest-only**: it proposes edits and never auto-commits.")
	w("  A human reviews and commits.")

	return b.String()
}

// codeList renders a string slice as a deterministic, comma-separated list of
// `code`-span values. An empty slice renders as "(none)". The input is not
// sorted — these vocabularies are ordered configuration, and preserving order
// keeps output stable and faithful to the resolved config.
func codeList(items []string) string {
	if len(items) == 0 {
		return "(none)"
	}
	parts := make([]string, len(items))
	for i, it := range items {
		parts[i] = "`" + it + "`"
	}
	return strings.Join(parts, ", ")
}
