#!/usr/bin/env bun
// Generates src/core/scaffold/embedded.ts — the init payload (base profiles +
// bundle skeleton + .claude mirror) embedded as a string manifest so a single
// compiled binary carries it. Replaces Go's `go:embed`. Run `bun run gen:embedded`
// after editing templates/; TestEmbedFresh is the drift gate.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const templatesDir = join(root, "templates");

export function buildManifest(): string {
  const files = [...new Bun.Glob("**/*").scanSync({ cwd: templatesDir, onlyFiles: true, dot: true })].sort();
  const lines = [
    "// GENERATED by scripts/gen-embedded.ts — do not edit. Run `bun run gen:embedded`.",
    "// The init payload (base profiles + bundle skeleton + .claude mirror) as data.",
    "export const TEMPLATES: Record<string, string> = {",
  ];
  for (const rel of files) {
    const key = rel.replaceAll("\\", "/");
    const content = readFileSync(join(templatesDir, rel), "utf8");
    lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(content)},`);
  }
  lines.push("};", "");
  return lines.join("\n");
}

if (import.meta.main) {
  const manifest = buildManifest();
  writeFileSync(join(root, "src", "core", "scaffold", "embedded.ts"), manifest);
  const n = (manifest.match(/^  "/gm) ?? []).length;
  console.log(`gen:embedded: ${n} files -> src/core/scaffold/embedded.ts`);
}
