// Generated, audience-readable stakeholder communications (SK-002/003/005):
// status reports and release notes derived deterministically from the repo.
// Suggest-only — these are drafts for human review; nothing is sent.
import type { Config } from "../config/config.ts";
import type { Registry } from "../types/registry.ts";
import type { Graph } from "../graphx/graph.ts";
import type { Finding } from "../model/model.ts";
import { buildStatus } from "../metrics/status.ts";

const DRAFT_NOTE = "_Generated by `iBuild report` — a draft for human review; nothing is sent automatically._";

// statusReport renders the progress/health dashboard as a stakeholder report (SK-003).
export function statusReport(graph: Graph, reg: Registry, cfg: Config, findings: Finding[]): string {
  const s = buildStatus(graph, reg, cfg, findings);
  const r = s.requirements;
  let md = `# Status Report\n\n${DRAFT_NOTE}\n\n`;
  md += `## Validation\n\n- ${s.validation.errors} error(s), ${s.validation.warnings} warning(s)\n\n`;
  md += `## Requirements\n\n- ${r.requirements} total · ${r.implemented} implemented · ${r.verified} verified · ${r.traced} fully traced\n\n`;
  md += `## Work by status\n\n`;
  for (const k of Object.keys(s.byStatus).sort()) md += `- ${k}: ${s.byStatus[k]}\n`;
  if (s.orphanActiveRequirements.length > 0) {
    md += `\n## Active requirements needing implementation\n\n`;
    for (const k of s.orphanActiveRequirements) md += `- ${k}\n`;
  }
  return md + "\n";
}

// releaseNotes lists work planned for a release, grouped by status (SK-002).
export function releaseNotes(graph: Graph, cfg: Config, releaseKey: string): string {
  const plannedRel = "planned_for"; // §9 release-planning relationship
  const planned = new Set(
    graph.edges.filter((e) => e.relationship === plannedRel && e.to === releaseKey && e.resolved).map((e) => e.from),
  );
  const done = new Set(cfg.chain.doneStatuses);
  const items = graph.nodes.filter((n) => planned.has(n.key));
  const shipped = items.filter((n) => done.has(n.status ?? "")).map((n) => n).sort((a, b) => (a.key < b.key ? -1 : 1));
  const pending = items.filter((n) => !done.has(n.status ?? "")).sort((a, b) => (a.key < b.key ? -1 : 1));

  const line = (n: { key: string; fields?: Record<string, unknown> }) =>
    `- ${typeof n.fields?.title === "string" ? n.fields.title : n.key} (${n.key})`;
  let md = `# Release Notes — ${releaseKey}\n\n${DRAFT_NOTE}\n\n`;
  md += `## Shipped (${shipped.length})\n\n` + (shipped.map(line).join("\n") || "_nothing yet_") + "\n\n";
  md += `## In progress (${pending.length})\n\n` + (pending.map(line).join("\n") || "_none_") + "\n";
  return md;
}
