// Emits the iBuildOS "contract surface": a deterministic, taxonomy-blind
// description of the binary and how OTHER coding agents drive it. AI-free; reads
// the resolved ChainConfig and renders stable Markdown. Port of Go
// internal/contract. Every name comes from cfg.chain (never a literal type name),
// so an alternate profile documents itself with zero code change.
import type { Config } from "../config/config.ts";

function codeList(items: string[]): string {
  if (items.length === 0) return "(none)";
  return items.map((it) => "`" + it + "`").join(", ");
}

export function agentsMD(cfg: Config, version: string): string {
  const ch = cfg.chain;
  return `# AGENTS.md — iBuildOS

iBuildOS is a **deterministic, AI-free traceability linter** for the
Requirement -> Task -> Code -> Test chain. Artifacts are OKF documents:
git-native Markdown files with YAML frontmatter. The linter is the single
source of truth for whether the chain is complete; it makes no network
calls and runs no AI.

This file follows the [AGENTS.md](https://agents.md) convention so any
coding agent or tool can drive iBuildOS by pointing at the binary and its
graph. It is generated by \`iBuild agents\` from the project's resolved
configuration; do not hand-edit.

Generated by iBuildOS ${version}.

## Commands

Use the \`iBuild\` binary. These are the surfaces an agent should drive:

- \`iBuild validate [path]\` — the **deterministic gate**. Exit code \`0\` means
  the chain is clean; exit code \`1\` means there are errors. Run this before
  declaring any work done; never bypass it. Add \`--format json\` for a stable
  machine report, or \`--changed\` to gate only changed artifacts.
- \`iBuild graph [path]\` — the typed link graph as JSON: the **fast-context
  oracle** for reasoning about the bundle. It computes no findings and is not
  a gate. Flags:
    - \`--node <ref>\` focus on one node (root-relative key) and its neighborhood
    - \`--depth N\` neighborhood radius when \`--node\` is set
    - \`--rel a,b\` restrict to these relationship names
    - \`--body excerpt|full|none\` how much node prose to include
- \`iBuild instructions [Type]\` — the authoring template for a type (from the
  project's \`docs/types/\`); no arg lists all defined types.

## The chain contract

Completeness rules key off these relationship and field names, resolved from
this project's configuration (an alternate profile renames them and this
document follows):

| Role | Name |
| --- | --- |
| work-fulfils-requirement relationship | \`${ch.implementsRel}\` |
| test-checks-requirement relationship | \`${ch.verifiesRel}\` |
| work-covered-by-test relationship | \`${ch.verifiedByRel}\` |
| work-rolls-up-to-work relationship | \`${ch.parentRel}\` |
| code field (globs to source files) | \`${ch.codeField}\` |

Status vocabularies (the one unavoidable value coupling):

- active requirement statuses: ${codeList(ch.activeReqStatuses)}
- proposed statuses: ${codeList(ch.proposedStatuses)}
- done statuses: ${codeList(ch.doneStatuses)}
- passing statuses: ${codeList(ch.passingStatuses)}

## Rules for agents

- Artifacts are git-native files. Edit the Markdown + frontmatter directly;
  state lives in git, never in a sidecar.
- Never bypass \`iBuild validate\`. It is the source of truth for the chain;
  if it reports errors, the work is not done.
- Use \`iBuild graph\` as your fast-context oracle before editing, so you
  reason over the actual typed link graph rather than guessing.
- AI authoring is **suggest-only**: it proposes edits and never auto-commits.
  A human reviews and commits.
`;
}
